/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	dolphiniov2alpha1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DolphinGatewayClassConfigLister helps list DolphinGatewayClassConfigs.
// All objects returned here must be treated as read-only.
type DolphinGatewayClassConfigLister interface {
	// List lists all DolphinGatewayClassConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dolphiniov2alpha1.DolphinGatewayClassConfig, err error)
	// DolphinGatewayClassConfigs returns an object that can list and get DolphinGatewayClassConfigs.
	DolphinGatewayClassConfigs(namespace string) DolphinGatewayClassConfigNamespaceLister
	DolphinGatewayClassConfigListerExpansion
}

// dolphinGatewayClassConfigLister implements the DolphinGatewayClassConfigLister interface.
type dolphinGatewayClassConfigLister struct {
	listers.ResourceIndexer[*dolphiniov2alpha1.DolphinGatewayClassConfig]
}

// NewDolphinGatewayClassConfigLister returns a new DolphinGatewayClassConfigLister.
func NewDolphinGatewayClassConfigLister(indexer cache.Indexer) DolphinGatewayClassConfigLister {
	return &dolphinGatewayClassConfigLister{listers.New[*dolphiniov2alpha1.DolphinGatewayClassConfig](indexer, dolphiniov2alpha1.Resource("dolphingatewayclassconfig"))}
}

// DolphinGatewayClassConfigs returns an object that can list and get DolphinGatewayClassConfigs.
func (s *dolphinGatewayClassConfigLister) DolphinGatewayClassConfigs(namespace string) DolphinGatewayClassConfigNamespaceLister {
	return dolphinGatewayClassConfigNamespaceLister{listers.NewNamespaced[*dolphiniov2alpha1.DolphinGatewayClassConfig](s.ResourceIndexer, namespace)}
}

// DolphinGatewayClassConfigNamespaceLister helps list and get DolphinGatewayClassConfigs.
// All objects returned here must be treated as read-only.
type DolphinGatewayClassConfigNamespaceLister interface {
	// List lists all DolphinGatewayClassConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dolphiniov2alpha1.DolphinGatewayClassConfig, err error)
	// Get retrieves the DolphinGatewayClassConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*dolphiniov2alpha1.DolphinGatewayClassConfig, error)
	DolphinGatewayClassConfigNamespaceListerExpansion
}

// dolphinGatewayClassConfigNamespaceLister implements the DolphinGatewayClassConfigNamespaceLister
// interface.
type dolphinGatewayClassConfigNamespaceLister struct {
	listers.ResourceIndexer[*dolphiniov2alpha1.DolphinGatewayClassConfig]
}
