/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	dolphiniov1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	versioned "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/ccfish2/infra/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/ccfish2/infra/pkg/k8s/client/listers/dolphin.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DolphinEndpointInformer provides access to a shared informer and lister for
// DolphinEndpoints.
type DolphinEndpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DolphinEndpointLister
}

type dolphinEndpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDolphinEndpointInformer constructs a new informer for DolphinEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDolphinEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDolphinEndpointInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDolphinEndpointInformer constructs a new informer for DolphinEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDolphinEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DolphinV1().DolphinEndpoints(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DolphinV1().DolphinEndpoints(namespace).Watch(context.TODO(), options)
			},
		},
		&dolphiniov1.DolphinEndpoint{},
		resyncPeriod,
		indexers,
	)
}

func (f *dolphinEndpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDolphinEndpointInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dolphinEndpointInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dolphiniov1.DolphinEndpoint{}, f.defaultInformer)
}

func (f *dolphinEndpointInformer) Lister() v1.DolphinEndpointLister {
	return v1.NewDolphinEndpointLister(f.Informer().GetIndexer())
}
