/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"

	dolphiniov2alpha1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v2alpha1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DolphinGatewayClassConfigsGetter has a method to return a DolphinGatewayClassConfigInterface.
// A group's client should implement this interface.
type DolphinGatewayClassConfigsGetter interface {
	DolphinGatewayClassConfigs(namespace string) DolphinGatewayClassConfigInterface
}

// DolphinGatewayClassConfigInterface has methods to work with DolphinGatewayClassConfig resources.
type DolphinGatewayClassConfigInterface interface {
	Create(ctx context.Context, dolphinGatewayClassConfig *dolphiniov2alpha1.DolphinGatewayClassConfig, opts v1.CreateOptions) (*dolphiniov2alpha1.DolphinGatewayClassConfig, error)
	Update(ctx context.Context, dolphinGatewayClassConfig *dolphiniov2alpha1.DolphinGatewayClassConfig, opts v1.UpdateOptions) (*dolphiniov2alpha1.DolphinGatewayClassConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dolphinGatewayClassConfig *dolphiniov2alpha1.DolphinGatewayClassConfig, opts v1.UpdateOptions) (*dolphiniov2alpha1.DolphinGatewayClassConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*dolphiniov2alpha1.DolphinGatewayClassConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*dolphiniov2alpha1.DolphinGatewayClassConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dolphiniov2alpha1.DolphinGatewayClassConfig, err error)
	DolphinGatewayClassConfigExpansion
}

// dolphinGatewayClassConfigs implements DolphinGatewayClassConfigInterface
type dolphinGatewayClassConfigs struct {
	*gentype.ClientWithList[*dolphiniov2alpha1.DolphinGatewayClassConfig, *dolphiniov2alpha1.DolphinGatewayClassConfigList]
}

// newDolphinGatewayClassConfigs returns a DolphinGatewayClassConfigs
func newDolphinGatewayClassConfigs(c *DolphinV2alpha1Client, namespace string) *dolphinGatewayClassConfigs {
	return &dolphinGatewayClassConfigs{
		gentype.NewClientWithList[*dolphiniov2alpha1.DolphinGatewayClassConfig, *dolphiniov2alpha1.DolphinGatewayClassConfigList](
			"dolphingatewayclassconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *dolphiniov2alpha1.DolphinGatewayClassConfig {
				return &dolphiniov2alpha1.DolphinGatewayClassConfig{}
			},
			func() *dolphiniov2alpha1.DolphinGatewayClassConfigList {
				return &dolphiniov2alpha1.DolphinGatewayClassConfigList{}
			},
		),
	}
}
