/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	dolphiniov1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DolphinEndpointsGetter has a method to return a DolphinEndpointInterface.
// A group's client should implement this interface.
type DolphinEndpointsGetter interface {
	DolphinEndpoints(namespace string) DolphinEndpointInterface
}

// DolphinEndpointInterface has methods to work with DolphinEndpoint resources.
type DolphinEndpointInterface interface {
	Create(ctx context.Context, dolphinEndpoint *dolphiniov1.DolphinEndpoint, opts metav1.CreateOptions) (*dolphiniov1.DolphinEndpoint, error)
	Update(ctx context.Context, dolphinEndpoint *dolphiniov1.DolphinEndpoint, opts metav1.UpdateOptions) (*dolphiniov1.DolphinEndpoint, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dolphinEndpoint *dolphiniov1.DolphinEndpoint, opts metav1.UpdateOptions) (*dolphiniov1.DolphinEndpoint, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*dolphiniov1.DolphinEndpoint, error)
	List(ctx context.Context, opts metav1.ListOptions) (*dolphiniov1.DolphinEndpointList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *dolphiniov1.DolphinEndpoint, err error)
	DolphinEndpointExpansion
}

// dolphinEndpoints implements DolphinEndpointInterface
type dolphinEndpoints struct {
	*gentype.ClientWithList[*dolphiniov1.DolphinEndpoint, *dolphiniov1.DolphinEndpointList]
}

// newDolphinEndpoints returns a DolphinEndpoints
func newDolphinEndpoints(c *DolphinV1Client, namespace string) *dolphinEndpoints {
	return &dolphinEndpoints{
		gentype.NewClientWithList[*dolphiniov1.DolphinEndpoint, *dolphiniov1.DolphinEndpointList](
			"dolphinendpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *dolphiniov1.DolphinEndpoint { return &dolphiniov1.DolphinEndpoint{} },
			func() *dolphiniov1.DolphinEndpointList { return &dolphiniov1.DolphinEndpointList{} },
		),
	}
}
