/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DolphinIdentitiesGetter has a method to return a DolphinIdentityInterface.
// A group's client should implement this interface.
type DolphinIdentitiesGetter interface {
	DolphinIdentities() DolphinIdentityInterface
}

// DolphinIdentityInterface has methods to work with DolphinIdentity resources.
type DolphinIdentityInterface interface {
	Create(ctx context.Context, dolphinIdentity *v1.DolphinIdentity, opts metav1.CreateOptions) (*v1.DolphinIdentity, error)
	Update(ctx context.Context, dolphinIdentity *v1.DolphinIdentity, opts metav1.UpdateOptions) (*v1.DolphinIdentity, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DolphinIdentity, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DolphinIdentityList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinIdentity, err error)
	DolphinIdentityExpansion
}

// dolphinIdentities implements DolphinIdentityInterface
type dolphinIdentities struct {
	client rest.Interface
}

// newDolphinIdentities returns a DolphinIdentities
func newDolphinIdentities(c *DolphinV1Client) *dolphinIdentities {
	return &dolphinIdentities{
		client: c.RESTClient(),
	}
}

// Get takes name of the dolphinIdentity, and returns the corresponding dolphinIdentity object, and an error if there is any.
func (c *dolphinIdentities) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DolphinIdentity, err error) {
	result = &v1.DolphinIdentity{}
	err = c.client.Get().
		Resource("dolphinidentities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DolphinIdentities that match those selectors.
func (c *dolphinIdentities) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DolphinIdentityList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DolphinIdentityList{}
	err = c.client.Get().
		Resource("dolphinidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dolphinIdentities.
func (c *dolphinIdentities) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dolphinidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dolphinIdentity and creates it.  Returns the server's representation of the dolphinIdentity, and an error, if there is any.
func (c *dolphinIdentities) Create(ctx context.Context, dolphinIdentity *v1.DolphinIdentity, opts metav1.CreateOptions) (result *v1.DolphinIdentity, err error) {
	result = &v1.DolphinIdentity{}
	err = c.client.Post().
		Resource("dolphinidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dolphinIdentity).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dolphinIdentity and updates it. Returns the server's representation of the dolphinIdentity, and an error, if there is any.
func (c *dolphinIdentities) Update(ctx context.Context, dolphinIdentity *v1.DolphinIdentity, opts metav1.UpdateOptions) (result *v1.DolphinIdentity, err error) {
	result = &v1.DolphinIdentity{}
	err = c.client.Put().
		Resource("dolphinidentities").
		Name(dolphinIdentity.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dolphinIdentity).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dolphinIdentity and deletes it. Returns an error if one occurs.
func (c *dolphinIdentities) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dolphinidentities").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dolphinIdentities) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dolphinidentities").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dolphinIdentity.
func (c *dolphinIdentities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinIdentity, err error) {
	result = &v1.DolphinIdentity{}
	err = c.client.Patch(pt).
		Resource("dolphinidentities").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
