/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	dolphiniov1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DolphinEndpointSlicesGetter has a method to return a DolphinEndpointSliceInterface.
// A group's client should implement this interface.
type DolphinEndpointSlicesGetter interface {
	DolphinEndpointSlices() DolphinEndpointSliceInterface
}

// DolphinEndpointSliceInterface has methods to work with DolphinEndpointSlice resources.
type DolphinEndpointSliceInterface interface {
	Create(ctx context.Context, dolphinEndpointSlice *dolphiniov1.DolphinEndpointSlice, opts metav1.CreateOptions) (*dolphiniov1.DolphinEndpointSlice, error)
	Update(ctx context.Context, dolphinEndpointSlice *dolphiniov1.DolphinEndpointSlice, opts metav1.UpdateOptions) (*dolphiniov1.DolphinEndpointSlice, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*dolphiniov1.DolphinEndpointSlice, error)
	List(ctx context.Context, opts metav1.ListOptions) (*dolphiniov1.DolphinEndpointSliceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *dolphiniov1.DolphinEndpointSlice, err error)
	DolphinEndpointSliceExpansion
}

// dolphinEndpointSlices implements DolphinEndpointSliceInterface
type dolphinEndpointSlices struct {
	*gentype.ClientWithList[*dolphiniov1.DolphinEndpointSlice, *dolphiniov1.DolphinEndpointSliceList]
}

// newDolphinEndpointSlices returns a DolphinEndpointSlices
func newDolphinEndpointSlices(c *DolphinV1Client) *dolphinEndpointSlices {
	return &dolphinEndpointSlices{
		gentype.NewClientWithList[*dolphiniov1.DolphinEndpointSlice, *dolphiniov1.DolphinEndpointSliceList](
			"dolphinendpointslices",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *dolphiniov1.DolphinEndpointSlice { return &dolphiniov1.DolphinEndpointSlice{} },
			func() *dolphiniov1.DolphinEndpointSliceList { return &dolphiniov1.DolphinEndpointSliceList{} },
		),
	}
}
