/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DolphinNodesGetter has a method to return a DolphinNodeInterface.
// A group's client should implement this interface.
type DolphinNodesGetter interface {
	DolphinNodes() DolphinNodeInterface
}

// DolphinNodeInterface has methods to work with DolphinNode resources.
type DolphinNodeInterface interface {
	Create(ctx context.Context, dolphinNode *v1.DolphinNode, opts metav1.CreateOptions) (*v1.DolphinNode, error)
	Update(ctx context.Context, dolphinNode *v1.DolphinNode, opts metav1.UpdateOptions) (*v1.DolphinNode, error)
	UpdateStatus(ctx context.Context, dolphinNode *v1.DolphinNode, opts metav1.UpdateOptions) (*v1.DolphinNode, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DolphinNode, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DolphinNodeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinNode, err error)
	DolphinNodeExpansion
}

// dolphinNodes implements DolphinNodeInterface
type dolphinNodes struct {
	client rest.Interface
}

// newDolphinNodes returns a DolphinNodes
func newDolphinNodes(c *DolphinV1Client) *dolphinNodes {
	return &dolphinNodes{
		client: c.RESTClient(),
	}
}

// Get takes name of the dolphinNode, and returns the corresponding dolphinNode object, and an error if there is any.
func (c *dolphinNodes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DolphinNode, err error) {
	result = &v1.DolphinNode{}
	err = c.client.Get().
		Resource("dolphinnodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DolphinNodes that match those selectors.
func (c *dolphinNodes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DolphinNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DolphinNodeList{}
	err = c.client.Get().
		Resource("dolphinnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dolphinNodes.
func (c *dolphinNodes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dolphinnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dolphinNode and creates it.  Returns the server's representation of the dolphinNode, and an error, if there is any.
func (c *dolphinNodes) Create(ctx context.Context, dolphinNode *v1.DolphinNode, opts metav1.CreateOptions) (result *v1.DolphinNode, err error) {
	result = &v1.DolphinNode{}
	err = c.client.Post().
		Resource("dolphinnodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dolphinNode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dolphinNode and updates it. Returns the server's representation of the dolphinNode, and an error, if there is any.
func (c *dolphinNodes) Update(ctx context.Context, dolphinNode *v1.DolphinNode, opts metav1.UpdateOptions) (result *v1.DolphinNode, err error) {
	result = &v1.DolphinNode{}
	err = c.client.Put().
		Resource("dolphinnodes").
		Name(dolphinNode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dolphinNode).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dolphinNodes) UpdateStatus(ctx context.Context, dolphinNode *v1.DolphinNode, opts metav1.UpdateOptions) (result *v1.DolphinNode, err error) {
	result = &v1.DolphinNode{}
	err = c.client.Put().
		Resource("dolphinnodes").
		Name(dolphinNode.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dolphinNode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dolphinNode and deletes it. Returns an error if one occurs.
func (c *dolphinNodes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dolphinnodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dolphinNodes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dolphinnodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dolphinNode.
func (c *dolphinNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinNode, err error) {
	result = &v1.DolphinNode{}
	err = c.client.Patch(pt).
		Resource("dolphinnodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
