/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	dolphiniov1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DolphinNodesGetter has a method to return a DolphinNodeInterface.
// A group's client should implement this interface.
type DolphinNodesGetter interface {
	DolphinNodes() DolphinNodeInterface
}

// DolphinNodeInterface has methods to work with DolphinNode resources.
type DolphinNodeInterface interface {
	Create(ctx context.Context, dolphinNode *dolphiniov1.DolphinNode, opts metav1.CreateOptions) (*dolphiniov1.DolphinNode, error)
	Update(ctx context.Context, dolphinNode *dolphiniov1.DolphinNode, opts metav1.UpdateOptions) (*dolphiniov1.DolphinNode, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dolphinNode *dolphiniov1.DolphinNode, opts metav1.UpdateOptions) (*dolphiniov1.DolphinNode, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*dolphiniov1.DolphinNode, error)
	List(ctx context.Context, opts metav1.ListOptions) (*dolphiniov1.DolphinNodeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *dolphiniov1.DolphinNode, err error)
	DolphinNodeExpansion
}

// dolphinNodes implements DolphinNodeInterface
type dolphinNodes struct {
	*gentype.ClientWithList[*dolphiniov1.DolphinNode, *dolphiniov1.DolphinNodeList]
}

// newDolphinNodes returns a DolphinNodes
func newDolphinNodes(c *DolphinV1Client) *dolphinNodes {
	return &dolphinNodes{
		gentype.NewClientWithList[*dolphiniov1.DolphinNode, *dolphiniov1.DolphinNodeList](
			"dolphinnodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *dolphiniov1.DolphinNode { return &dolphiniov1.DolphinNode{} },
			func() *dolphiniov1.DolphinNodeList { return &dolphiniov1.DolphinNodeList{} },
		),
	}
}
