/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	dolphiniov1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DolphinIdentitiesGetter has a method to return a DolphinIdentityInterface.
// A group's client should implement this interface.
type DolphinIdentitiesGetter interface {
	DolphinIdentities() DolphinIdentityInterface
}

// DolphinIdentityInterface has methods to work with DolphinIdentity resources.
type DolphinIdentityInterface interface {
	Create(ctx context.Context, dolphinIdentity *dolphiniov1.DolphinIdentity, opts metav1.CreateOptions) (*dolphiniov1.DolphinIdentity, error)
	Update(ctx context.Context, dolphinIdentity *dolphiniov1.DolphinIdentity, opts metav1.UpdateOptions) (*dolphiniov1.DolphinIdentity, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*dolphiniov1.DolphinIdentity, error)
	List(ctx context.Context, opts metav1.ListOptions) (*dolphiniov1.DolphinIdentityList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *dolphiniov1.DolphinIdentity, err error)
	DolphinIdentityExpansion
}

// dolphinIdentities implements DolphinIdentityInterface
type dolphinIdentities struct {
	*gentype.ClientWithList[*dolphiniov1.DolphinIdentity, *dolphiniov1.DolphinIdentityList]
}

// newDolphinIdentities returns a DolphinIdentities
func newDolphinIdentities(c *DolphinV1Client) *dolphinIdentities {
	return &dolphinIdentities{
		gentype.NewClientWithList[*dolphiniov1.DolphinIdentity, *dolphiniov1.DolphinIdentityList](
			"dolphinidentities",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *dolphiniov1.DolphinIdentity { return &dolphiniov1.DolphinIdentity{} },
			func() *dolphiniov1.DolphinIdentityList { return &dolphiniov1.DolphinIdentityList{} },
		),
	}
}
