/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	scheme "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DolphinEndpointSlicesGetter has a method to return a DolphinEndpointSliceInterface.
// A group's client should implement this interface.
type DolphinEndpointSlicesGetter interface {
	DolphinEndpointSlices() DolphinEndpointSliceInterface
}

// DolphinEndpointSliceInterface has methods to work with DolphinEndpointSlice resources.
type DolphinEndpointSliceInterface interface {
	Create(ctx context.Context, dolphinEndpointSlice *v1.DolphinEndpointSlice, opts metav1.CreateOptions) (*v1.DolphinEndpointSlice, error)
	Update(ctx context.Context, dolphinEndpointSlice *v1.DolphinEndpointSlice, opts metav1.UpdateOptions) (*v1.DolphinEndpointSlice, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DolphinEndpointSlice, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DolphinEndpointSliceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinEndpointSlice, err error)
	DolphinEndpointSliceExpansion
}

// dolphinEndpointSlices implements DolphinEndpointSliceInterface
type dolphinEndpointSlices struct {
	client rest.Interface
}

// newDolphinEndpointSlices returns a DolphinEndpointSlices
func newDolphinEndpointSlices(c *DolphinV1Client) *dolphinEndpointSlices {
	return &dolphinEndpointSlices{
		client: c.RESTClient(),
	}
}

// Get takes name of the dolphinEndpointSlice, and returns the corresponding dolphinEndpointSlice object, and an error if there is any.
func (c *dolphinEndpointSlices) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DolphinEndpointSlice, err error) {
	result = &v1.DolphinEndpointSlice{}
	err = c.client.Get().
		Resource("dolphinendpointslices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DolphinEndpointSlices that match those selectors.
func (c *dolphinEndpointSlices) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DolphinEndpointSliceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DolphinEndpointSliceList{}
	err = c.client.Get().
		Resource("dolphinendpointslices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dolphinEndpointSlices.
func (c *dolphinEndpointSlices) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dolphinendpointslices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dolphinEndpointSlice and creates it.  Returns the server's representation of the dolphinEndpointSlice, and an error, if there is any.
func (c *dolphinEndpointSlices) Create(ctx context.Context, dolphinEndpointSlice *v1.DolphinEndpointSlice, opts metav1.CreateOptions) (result *v1.DolphinEndpointSlice, err error) {
	result = &v1.DolphinEndpointSlice{}
	err = c.client.Post().
		Resource("dolphinendpointslices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dolphinEndpointSlice).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dolphinEndpointSlice and updates it. Returns the server's representation of the dolphinEndpointSlice, and an error, if there is any.
func (c *dolphinEndpointSlices) Update(ctx context.Context, dolphinEndpointSlice *v1.DolphinEndpointSlice, opts metav1.UpdateOptions) (result *v1.DolphinEndpointSlice, err error) {
	result = &v1.DolphinEndpointSlice{}
	err = c.client.Put().
		Resource("dolphinendpointslices").
		Name(dolphinEndpointSlice.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dolphinEndpointSlice).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dolphinEndpointSlice and deletes it. Returns an error if one occurs.
func (c *dolphinEndpointSlices) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dolphinendpointslices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dolphinEndpointSlices) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dolphinendpointslices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dolphinEndpointSlice.
func (c *dolphinEndpointSlices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinEndpointSlice, err error) {
	result = &v1.DolphinEndpointSlice{}
	err = c.client.Patch(pt).
		Resource("dolphinendpointslices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
