/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDolphinEndpoints implements DolphinEndpointInterface
type FakeDolphinEndpoints struct {
	Fake *FakeDolphinV1
	ns   string
}

var dolphinendpointsResource = v1.SchemeGroupVersion.WithResource("dolphinendpoints")

var dolphinendpointsKind = v1.SchemeGroupVersion.WithKind("DolphinEndpoint")

// Get takes name of the dolphinEndpoint, and returns the corresponding dolphinEndpoint object, and an error if there is any.
func (c *FakeDolphinEndpoints) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DolphinEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dolphinendpointsResource, c.ns, name), &v1.DolphinEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEndpoint), err
}

// List takes label and field selectors, and returns the list of DolphinEndpoints that match those selectors.
func (c *FakeDolphinEndpoints) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DolphinEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dolphinendpointsResource, dolphinendpointsKind, c.ns, opts), &v1.DolphinEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DolphinEndpointList{ListMeta: obj.(*v1.DolphinEndpointList).ListMeta}
	for _, item := range obj.(*v1.DolphinEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dolphinEndpoints.
func (c *FakeDolphinEndpoints) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dolphinendpointsResource, c.ns, opts))

}

// Create takes the representation of a dolphinEndpoint and creates it.  Returns the server's representation of the dolphinEndpoint, and an error, if there is any.
func (c *FakeDolphinEndpoints) Create(ctx context.Context, dolphinEndpoint *v1.DolphinEndpoint, opts metav1.CreateOptions) (result *v1.DolphinEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dolphinendpointsResource, c.ns, dolphinEndpoint), &v1.DolphinEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEndpoint), err
}

// Update takes the representation of a dolphinEndpoint and updates it. Returns the server's representation of the dolphinEndpoint, and an error, if there is any.
func (c *FakeDolphinEndpoints) Update(ctx context.Context, dolphinEndpoint *v1.DolphinEndpoint, opts metav1.UpdateOptions) (result *v1.DolphinEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dolphinendpointsResource, c.ns, dolphinEndpoint), &v1.DolphinEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEndpoint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDolphinEndpoints) UpdateStatus(ctx context.Context, dolphinEndpoint *v1.DolphinEndpoint, opts metav1.UpdateOptions) (*v1.DolphinEndpoint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dolphinendpointsResource, "status", c.ns, dolphinEndpoint), &v1.DolphinEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEndpoint), err
}

// Delete takes name of the dolphinEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeDolphinEndpoints) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dolphinendpointsResource, c.ns, name, opts), &v1.DolphinEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDolphinEndpoints) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dolphinendpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DolphinEndpointList{})
	return err
}

// Patch applies the patch and returns the patched dolphinEndpoint.
func (c *FakeDolphinEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dolphinendpointsResource, c.ns, name, pt, data, subresources...), &v1.DolphinEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEndpoint), err
}
