/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDolphinEnvoyConfigs implements DolphinEnvoyConfigInterface
type FakeDolphinEnvoyConfigs struct {
	Fake *FakeDolphinV1
	ns   string
}

var dolphinenvoyconfigsResource = v1.SchemeGroupVersion.WithResource("dolphinenvoyconfigs")

var dolphinenvoyconfigsKind = v1.SchemeGroupVersion.WithKind("DolphinEnvoyConfig")

// Get takes name of the dolphinEnvoyConfig, and returns the corresponding dolphinEnvoyConfig object, and an error if there is any.
func (c *FakeDolphinEnvoyConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DolphinEnvoyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dolphinenvoyconfigsResource, c.ns, name), &v1.DolphinEnvoyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEnvoyConfig), err
}

// List takes label and field selectors, and returns the list of DolphinEnvoyConfigs that match those selectors.
func (c *FakeDolphinEnvoyConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DolphinEnvoyConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dolphinenvoyconfigsResource, dolphinenvoyconfigsKind, c.ns, opts), &v1.DolphinEnvoyConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DolphinEnvoyConfigList{ListMeta: obj.(*v1.DolphinEnvoyConfigList).ListMeta}
	for _, item := range obj.(*v1.DolphinEnvoyConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dolphinEnvoyConfigs.
func (c *FakeDolphinEnvoyConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dolphinenvoyconfigsResource, c.ns, opts))

}

// Create takes the representation of a dolphinEnvoyConfig and creates it.  Returns the server's representation of the dolphinEnvoyConfig, and an error, if there is any.
func (c *FakeDolphinEnvoyConfigs) Create(ctx context.Context, dolphinEnvoyConfig *v1.DolphinEnvoyConfig, opts metav1.CreateOptions) (result *v1.DolphinEnvoyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dolphinenvoyconfigsResource, c.ns, dolphinEnvoyConfig), &v1.DolphinEnvoyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEnvoyConfig), err
}

// Update takes the representation of a dolphinEnvoyConfig and updates it. Returns the server's representation of the dolphinEnvoyConfig, and an error, if there is any.
func (c *FakeDolphinEnvoyConfigs) Update(ctx context.Context, dolphinEnvoyConfig *v1.DolphinEnvoyConfig, opts metav1.UpdateOptions) (result *v1.DolphinEnvoyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dolphinenvoyconfigsResource, c.ns, dolphinEnvoyConfig), &v1.DolphinEnvoyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEnvoyConfig), err
}

// Delete takes name of the dolphinEnvoyConfig and deletes it. Returns an error if one occurs.
func (c *FakeDolphinEnvoyConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dolphinenvoyconfigsResource, c.ns, name, opts), &v1.DolphinEnvoyConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDolphinEnvoyConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dolphinenvoyconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DolphinEnvoyConfigList{})
	return err
}

// Patch applies the patch and returns the patched dolphinEnvoyConfig.
func (c *FakeDolphinEnvoyConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinEnvoyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dolphinenvoyconfigsResource, c.ns, name, pt, data, subresources...), &v1.DolphinEnvoyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinEnvoyConfig), err
}
