/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDolphinIdentities implements DolphinIdentityInterface
type FakeDolphinIdentities struct {
	Fake *FakeDolphinV1
}

var dolphinidentitiesResource = v1.SchemeGroupVersion.WithResource("dolphinidentities")

var dolphinidentitiesKind = v1.SchemeGroupVersion.WithKind("DolphinIdentity")

// Get takes name of the dolphinIdentity, and returns the corresponding dolphinIdentity object, and an error if there is any.
func (c *FakeDolphinIdentities) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DolphinIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(dolphinidentitiesResource, name), &v1.DolphinIdentity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinIdentity), err
}

// List takes label and field selectors, and returns the list of DolphinIdentities that match those selectors.
func (c *FakeDolphinIdentities) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DolphinIdentityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(dolphinidentitiesResource, dolphinidentitiesKind, opts), &v1.DolphinIdentityList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DolphinIdentityList{ListMeta: obj.(*v1.DolphinIdentityList).ListMeta}
	for _, item := range obj.(*v1.DolphinIdentityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dolphinIdentities.
func (c *FakeDolphinIdentities) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(dolphinidentitiesResource, opts))
}

// Create takes the representation of a dolphinIdentity and creates it.  Returns the server's representation of the dolphinIdentity, and an error, if there is any.
func (c *FakeDolphinIdentities) Create(ctx context.Context, dolphinIdentity *v1.DolphinIdentity, opts metav1.CreateOptions) (result *v1.DolphinIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dolphinidentitiesResource, dolphinIdentity), &v1.DolphinIdentity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinIdentity), err
}

// Update takes the representation of a dolphinIdentity and updates it. Returns the server's representation of the dolphinIdentity, and an error, if there is any.
func (c *FakeDolphinIdentities) Update(ctx context.Context, dolphinIdentity *v1.DolphinIdentity, opts metav1.UpdateOptions) (result *v1.DolphinIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(dolphinidentitiesResource, dolphinIdentity), &v1.DolphinIdentity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinIdentity), err
}

// Delete takes name of the dolphinIdentity and deletes it. Returns an error if one occurs.
func (c *FakeDolphinIdentities) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(dolphinidentitiesResource, name, opts), &v1.DolphinIdentity{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDolphinIdentities) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(dolphinidentitiesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DolphinIdentityList{})
	return err
}

// Patch applies the patch and returns the patched dolphinIdentity.
func (c *FakeDolphinIdentities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DolphinIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(dolphinidentitiesResource, name, pt, data, subresources...), &v1.DolphinIdentity{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DolphinIdentity), err
}
