/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"
	time "time"

	apisdolphiniov2alpha1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v2alpha1"
	versioned "github.com/ccfish2/infra/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/ccfish2/infra/pkg/k8s/client/informers/externalversions/internalinterfaces"
	dolphiniov2alpha1 "github.com/ccfish2/infra/pkg/k8s/client/listers/dolphin.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DolphinGatewayClassConfigInformer provides access to a shared informer and lister for
// DolphinGatewayClassConfigs.
type DolphinGatewayClassConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() dolphiniov2alpha1.DolphinGatewayClassConfigLister
}

type dolphinGatewayClassConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDolphinGatewayClassConfigInformer constructs a new informer for DolphinGatewayClassConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDolphinGatewayClassConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDolphinGatewayClassConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDolphinGatewayClassConfigInformer constructs a new informer for DolphinGatewayClassConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDolphinGatewayClassConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DolphinV2alpha1().DolphinGatewayClassConfigs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DolphinV2alpha1().DolphinGatewayClassConfigs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DolphinV2alpha1().DolphinGatewayClassConfigs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DolphinV2alpha1().DolphinGatewayClassConfigs(namespace).Watch(ctx, options)
			},
		}, client),
		&apisdolphiniov2alpha1.DolphinGatewayClassConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *dolphinGatewayClassConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDolphinGatewayClassConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dolphinGatewayClassConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdolphiniov2alpha1.DolphinGatewayClassConfig{}, f.defaultInformer)
}

func (f *dolphinGatewayClassConfigInformer) Lister() dolphiniov2alpha1.DolphinGatewayClassConfigLister {
	return dolphiniov2alpha1.NewDolphinGatewayClassConfigLister(f.Informer().GetIndexer())
}
