/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DolphinEnvoyConfigLister helps list DolphinEnvoyConfigs.
// All objects returned here must be treated as read-only.
type DolphinEnvoyConfigLister interface {
	// List lists all DolphinEnvoyConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DolphinEnvoyConfig, err error)
	// DolphinEnvoyConfigs returns an object that can list and get DolphinEnvoyConfigs.
	DolphinEnvoyConfigs(namespace string) DolphinEnvoyConfigNamespaceLister
	DolphinEnvoyConfigListerExpansion
}

// dolphinEnvoyConfigLister implements the DolphinEnvoyConfigLister interface.
type dolphinEnvoyConfigLister struct {
	indexer cache.Indexer
}

// NewDolphinEnvoyConfigLister returns a new DolphinEnvoyConfigLister.
func NewDolphinEnvoyConfigLister(indexer cache.Indexer) DolphinEnvoyConfigLister {
	return &dolphinEnvoyConfigLister{indexer: indexer}
}

// List lists all DolphinEnvoyConfigs in the indexer.
func (s *dolphinEnvoyConfigLister) List(selector labels.Selector) (ret []*v1.DolphinEnvoyConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DolphinEnvoyConfig))
	})
	return ret, err
}

// DolphinEnvoyConfigs returns an object that can list and get DolphinEnvoyConfigs.
func (s *dolphinEnvoyConfigLister) DolphinEnvoyConfigs(namespace string) DolphinEnvoyConfigNamespaceLister {
	return dolphinEnvoyConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// DolphinEnvoyConfigNamespaceLister helps list and get DolphinEnvoyConfigs.
// All objects returned here must be treated as read-only.
type DolphinEnvoyConfigNamespaceLister interface {
	// List lists all DolphinEnvoyConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DolphinEnvoyConfig, err error)
	// Get retrieves the DolphinEnvoyConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DolphinEnvoyConfig, error)
	DolphinEnvoyConfigNamespaceListerExpansion
}

// dolphinEnvoyConfigNamespaceLister implements the DolphinEnvoyConfigNamespaceLister
// interface.
type dolphinEnvoyConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all DolphinEnvoyConfigs in the indexer for a given namespace.
func (s dolphinEnvoyConfigNamespaceLister) List(selector labels.Selector) (ret []*v1.DolphinEnvoyConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DolphinEnvoyConfig))
	})
	return ret, err
}

// Get retrieves the DolphinEnvoyConfig from the indexer for a given namespace and name.
func (s dolphinEnvoyConfigNamespaceLister) Get(name string) (*v1.DolphinEnvoyConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("dolphinenvoyconfig"), name)
	}
	return obj.(*v1.DolphinEnvoyConfig), nil
}
