/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DolphinEndpointSliceLister helps list DolphinEndpointSlices.
// All objects returned here must be treated as read-only.
type DolphinEndpointSliceLister interface {
	// List lists all DolphinEndpointSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DolphinEndpointSlice, err error)
	// Get retrieves the DolphinEndpointSlice from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DolphinEndpointSlice, error)
	DolphinEndpointSliceListerExpansion
}

// dolphinEndpointSliceLister implements the DolphinEndpointSliceLister interface.
type dolphinEndpointSliceLister struct {
	indexer cache.Indexer
}

// NewDolphinEndpointSliceLister returns a new DolphinEndpointSliceLister.
func NewDolphinEndpointSliceLister(indexer cache.Indexer) DolphinEndpointSliceLister {
	return &dolphinEndpointSliceLister{indexer: indexer}
}

// List lists all DolphinEndpointSlices in the indexer.
func (s *dolphinEndpointSliceLister) List(selector labels.Selector) (ret []*v1.DolphinEndpointSlice, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DolphinEndpointSlice))
	})
	return ret, err
}

// Get retrieves the DolphinEndpointSlice from the index for a given name.
func (s *dolphinEndpointSliceLister) Get(name string) (*v1.DolphinEndpointSlice, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("dolphinendpointslice"), name)
	}
	return obj.(*v1.DolphinEndpointSlice), nil
}
