/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	dolphiniov1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DolphinEndpointLister helps list DolphinEndpoints.
// All objects returned here must be treated as read-only.
type DolphinEndpointLister interface {
	// List lists all DolphinEndpoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dolphiniov1.DolphinEndpoint, err error)
	// DolphinEndpoints returns an object that can list and get DolphinEndpoints.
	DolphinEndpoints(namespace string) DolphinEndpointNamespaceLister
	DolphinEndpointListerExpansion
}

// dolphinEndpointLister implements the DolphinEndpointLister interface.
type dolphinEndpointLister struct {
	listers.ResourceIndexer[*dolphiniov1.DolphinEndpoint]
}

// NewDolphinEndpointLister returns a new DolphinEndpointLister.
func NewDolphinEndpointLister(indexer cache.Indexer) DolphinEndpointLister {
	return &dolphinEndpointLister{listers.New[*dolphiniov1.DolphinEndpoint](indexer, dolphiniov1.Resource("dolphinendpoint"))}
}

// DolphinEndpoints returns an object that can list and get DolphinEndpoints.
func (s *dolphinEndpointLister) DolphinEndpoints(namespace string) DolphinEndpointNamespaceLister {
	return dolphinEndpointNamespaceLister{listers.NewNamespaced[*dolphiniov1.DolphinEndpoint](s.ResourceIndexer, namespace)}
}

// DolphinEndpointNamespaceLister helps list and get DolphinEndpoints.
// All objects returned here must be treated as read-only.
type DolphinEndpointNamespaceLister interface {
	// List lists all DolphinEndpoints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dolphiniov1.DolphinEndpoint, err error)
	// Get retrieves the DolphinEndpoint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*dolphiniov1.DolphinEndpoint, error)
	DolphinEndpointNamespaceListerExpansion
}

// dolphinEndpointNamespaceLister implements the DolphinEndpointNamespaceLister
// interface.
type dolphinEndpointNamespaceLister struct {
	listers.ResourceIndexer[*dolphiniov1.DolphinEndpoint]
}
