/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	dolphiniov1 "github.com/ccfish2/infra/pkg/k8s/apis/dolphin.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DolphinIdentityLister helps list DolphinIdentities.
// All objects returned here must be treated as read-only.
type DolphinIdentityLister interface {
	// List lists all DolphinIdentities in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dolphiniov1.DolphinIdentity, err error)
	// Get retrieves the DolphinIdentity from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*dolphiniov1.DolphinIdentity, error)
	DolphinIdentityListerExpansion
}

// dolphinIdentityLister implements the DolphinIdentityLister interface.
type dolphinIdentityLister struct {
	listers.ResourceIndexer[*dolphiniov1.DolphinIdentity]
}

// NewDolphinIdentityLister returns a new DolphinIdentityLister.
func NewDolphinIdentityLister(indexer cache.Indexer) DolphinIdentityLister {
	return &dolphinIdentityLister{listers.New[*dolphiniov1.DolphinIdentity](indexer, dolphiniov1.Resource("dolphinidentity"))}
}
