/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// DolphinEndpointListerExpansion allows custom methods to be added to
// DolphinEndpointLister.
type DolphinEndpointListerExpansion interface{}

// DolphinEndpointNamespaceListerExpansion allows custom methods to be added to
// DolphinEndpointNamespaceLister.
type DolphinEndpointNamespaceListerExpansion interface{}

// DolphinEndpointSliceListerExpansion allows custom methods to be added to
// DolphinEndpointSliceLister.
type DolphinEndpointSliceListerExpansion interface{}

// DolphinEnvoyConfigListerExpansion allows custom methods to be added to
// DolphinEnvoyConfigLister.
type DolphinEnvoyConfigListerExpansion interface{}

// DolphinEnvoyConfigNamespaceListerExpansion allows custom methods to be added to
// DolphinEnvoyConfigNamespaceLister.
type DolphinEnvoyConfigNamespaceListerExpansion interface{}

// DolphinIdentityListerExpansion allows custom methods to be added to
// DolphinIdentityLister.
type DolphinIdentityListerExpansion interface{}

// DolphinNodeListerExpansion allows custom methods to be added to
// DolphinNodeLister.
type DolphinNodeListerExpansion interface{}
