go list ./... | grep -v metalb0110 | grep -vE 'pkg/bgp/k8s|pkg/bgp/log' > packages.txt

# Run tests only where *_integration_test.go files exist
for pkg in $(cat packages.txt); do
  if ls $(go list -f '{{.Dir}}' $pkg)/*_test.go > /dev/null 2>&1; then
    go test -v $pkg
  fi
done
