name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1.0.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run tests with coverage
        run: |
          go list ./... | grep -v metalb0110 | grep -vE 'pkg/bgp/k8s|pkg/bgp/log' > packages.txt

          # Run tests only where *_integration_test.go files exist
          for pkg in $(cat packages.txt); do
            if ls $(go list -f '{{.Dir}}' $pkg)/*_test.go > /dev/null 2>&1; then
              go test -v $pkg
            fi
          done

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
