name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1.0.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run tests with coverage
        run: |
           # Get list of your own packages
          go list ./... | grep -v metalb0110 | grep -vE 'pkg/bgp/k8s|pkg/bgp/log' > packages.txt
            # Run tests only for packages that can compile AND have tests
          for pkg in $(cat packages.txt); do
            # Run coverage test ONLY IF the package has test files and can compile
            if ls $(go list -f '{{.Dir}}' $pkg)/*_test.go > /dev/null 2>&1; then
              go test -coverpkg=./... -coverprofile=coverage.$(basename $pkg).out -run=. $pkg || echo "Skipped $pkg"
            fi
          done
          
          # Combine all coverage files
          echo "mode: set" > coverage.out
          tail -q -n +2 coverage.*.out >> coverage.out
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
